### ISSUE TITLE
常驻进程和WebApi服务化

### ISSUE THREAD

**Issue by kiss291323003** [zhouaini528/exchanges-php#11]
有没有考虑过利用easyswoole的自定义进程+定时器，还有协程。实现常驻内存化的自动化交易管理服务。https://github.com/easy-swoole/easyswoole

**Comment by zhouaini528** [comment]
很早之前我有考虑过用swoole，但是最后选择workerman，原因有几点~1：swoole需要单独的环境，对于新手来讲不是很友好，还需要单独安装。    2：该SDK其实对性能上的要求其实并不高，只是websocket这块服务。    3：该SDK只做针对接口的数据交互，避免涉及到业务相关~使用者完全可以独立该模块~比如order account存放在数据库或者cache中~业务通过数据库或cache来交易管理。

**Comment by zhouaini528** [comment]
你这么一说，我也许后期会做WebApi服务化，比如说~获取到的数据主动推送。谢谢你的的意见
