### ISSUE TITLE
请问几时会支持 Websocket 呢？

### ISSUE THREAD

**Issue by mirror222** [zhouaini528/exchanges-php#12]
谢谢

**Comment by zhouaini528** [comment]
你好目前支持以下几个交易所

[Bitmex](https://github.com/zhouaini528/bitmex-php) 支持[Websocket](https://github.com/zhouaini528/bitmex-php/blob/master/README_CN.md#Websocket)

[Okex](https://github.com/zhouaini528/okex-php) 支持[Websocket](https://github.com/zhouaini528/okex-php/blob/master/README_CN.md#Websocket)

[Huobi](https://github.com/zhouaini528/huobi-php) 支持[Websocket](https://github.com/zhouaini528/huobi-php/blob/master/README_CN.md#Websocket)

[Binance](https://github.com/zhouaini528/binance-php) 支持[Websocket](https://github.com/zhouaini528/binance-php/blob/master/README_CN.md#Websocket)

exchanges-php该SDK目前暂时没有集成进来，  但是不影响你单独使用。你引用了exchanges-php包，你就可以直接
```php
use \Lin\Binance\BinanceWebSocket;
$binance=new BinanceWebSocket();
$binance->config();

use \Lin\Huobi\HuobiWebSocket;
$huobi=new HuobiWebSocket();
$huobi->config();

......
......
......
```

**Comment by mirror222** [comment]
感谢作者！
