### ISSUE TITLE
Adding exchanges

### ISSUE THREAD

**Issue by placzkowski** [zhouaini528/exchanges-php#13]
Hi, maybe you could add Poloniex exchange? Do you think about adding uniswap/pancakeswap?

**Comment by zhouaini528** [comment]
Thank you for your suggestion. I will consider adding Poloniex. uniswap/pancakeswap I haven't figured out how to join it.

**Comment by zhouaini528** [comment]
Hi,I have finished it and I can give you any feedback if you have any questions.   [https://github.com/zhouaini528/poloniex-php](https://github.com/zhouaini528/poloniex-php)
