### ISSUE TITLE
okex V5 的 websocket 能出一个相关的使用示例吗？

### ISSUE THREAD

**Issue by wf58585858** [zhouaini528/exchanges-php#14]
两个小请求
1，目前okex websocket  只有 v3 的封装，如果可以能否封装一下v5的谢谢

2，目前用工厂获取的是 v3的实例，可以适配一下  v5 的
可以类似这样 `$exchanges = new Exchanges('okexV5');`
这个目前使用起来问题不大，我目前是这样使用的 `new \Lin\Okex\OkexV5 `

主要是第一个，谢谢！

**Comment by zhouaini528** [comment]
可以的  okex v5  我会近期把它加入进去。你目前用v5 只能new \Lin\Okex\OkexV5

**Comment by wf58585858** [comment]
十分感谢，主要是 websocket 那个，我考虑的是所有的调用都使用它，实时性比较强

**Comment by zhouaini528** [comment]
https://github.com/zhouaini528/okex-php/blob/master/README.md#Websocket
