### ISSUE TITLE
添加 coinex 么？

### ISSUE THREAD

**Issue by Time02** [zhouaini528/exchanges-php#17]

**Comment by zhouaini528** [comment]
可以的，但是需要一点时间，你还有什么需求？

**Comment by Time02** [comment]
没有了  : )

**Comment by zhouaini528** [comment]
我完成了现货，还剩下期货， 的下周去了。[https://github.com/zhouaini528/coinex-php](https://github.com/zhouaini528/coinex-php)

**Comment by zhouaini528** [comment]
我看了你fock了 binance的项目还做了一些更改，  我觉得很好，  你应该pull给我，避免分支过多。也更好的维护它

**Comment by zhouaini528** [comment]
对了你可以加qq群： 668421169    可以提出你的问题和需求

**Comment by Time02** [comment]
OK，已经加了
