### ISSUE TITLE
Hello，does your team develop golang exchanges sdk，big old ?

### ISSUE THREAD

**Issue by JackSeven** [zhouaini528/exchanges-php#20]
Just like the issue I asked, if it is true, please la me yi xia，OK ？^_^

**Comment by zhouaini528** [comment]
PHP does not use golang because the integration with exchanges considers comprehensive cost performance, and the main performance bottleneck is the network IO problem. There is a good SDK here to find out [https://github.com/nntaoli-project/goex](https://github.com/nntaoli-project/goex)

**Comment by JackSeven** [comment]
> PHP does not use golang because the integration with exchanges considers comprehensive cost performance, and the main performance bottleneck is the network IO problem. There is a good SDK here to find out https://github.com/nntaoli-project/goex

very kind of you , thanks
