### ISSUE TITLE
请问一下，是不是有很多API还没有写完？例如火币 查询历史订单 查询订单详情等等

### ISSUE THREAD

**Issue by ChenRuihua** [zhouaini528/exchanges-php#3]
如题，谢谢。

**Comment by zhouaini528** [comment]
是的。很多接口还没有完善，但是底层接口是完善了的。exchanges-php它只是一个抽象层，你可以看它引用的包 bitmex okex等等，主要为了低耦合。如果你有特殊的需求你可以[$exchanges->getPlatform()](https://github.com/zhouaini528/exchanges-php/blob/master/README_CN.md#%E6%94%AF%E6%8C%81%E5%8E%9F%E5%A7%8B%E5%AF%B9%E8%B1%A1%E8%AF%B7%E6%B1%82)这个方法来获取。

**Comment by zhouaini528** [comment]
查询订单是有的[点击$exchanges->trader()->show()](https://github.com/zhouaini528/exchanges-php/blob/master/src/Api/Trader.php#L181)。你可以看源码我封装在了buy sell里面，你也可以单独查询。

**Comment by ChenRuihua** [comment]
谢谢你了。大概研究了一下源码，Account类下的position这个方法是做什么用的呢？

**Comment by zhouaini528** [comment]
这个算我留的一个小坑，其实没什么用，后面我再整理一下没有用的暂时不写出来。当初的设计思想是这个SDK包含所有的交易所，现货市场okex huobi获取余额是Account Get ,而bitmex 是position。   我待会去备注一下，方便大家看源码。   这sdk还有很多未完善的地方，希望大家多多提意见哈

**Comment by ChenRuihua** [comment]
谢谢，我主要是用火币。bitmex的api还没看过，打算写一个网格交易策略的机器人，让程序来炒币，人性太难控制了。所以还是交给机器靠谱。祝作者币圈大赚。

**Comment by zhouaini528** [comment]
如果以后不用其他平台可以直接用[Huobi Api](https://github.com/zhouaini528/huobi-php/blob/master/README_CN.md) ，Exchanges也是基于它再次封装的，它可以满足你所有要求。 但是根据你说情况  我还是建议你用Exchanges 这个SDK，你就是买卖查询和查询余额应该能满足你所有的了。
