### ISSUE TITLE
你好，我现在很头痛，一直出现这个问题，这个问题怎么解决呢，我单独写OK,或者币安没有出现这个问题呢

### ISSUE THREAD

**Issue by yeshili** [zhouaini528/exchanges-php#5]
Array ( [_error] => Array ( [_message] => cURL error 7: Failed to connect to www.okex.com port 443: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [_httpcode] => 0 ) )

**Comment by yeshili** [comment]
所有的交易所都出现这个问题，huobi,binance都一样呢！

**Comment by yeshili** [comment]
请求了huobi就返回这样的错误Array ( [_error] => Array ( [_message] => cURL error 7: Failed to connect to api.huobi.pro port 443: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [_httpcode] => 0 ) )

**Comment by zhouaini528** [comment]
你把代码 贴出来我看看，   key  secret 你保密做处理。

**Comment by yeshili** [comment]
Array ( [_error] => Array ( [_message] => cURL error 7: Failed to connect to api.binance.com port 443: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [_httpcode] => 0 ) )

![图片](https://user-images.githubusercontent.com/24773628/85943859-5d842c00-b965-11ea-9314-734bf70b8569.png)

**Comment by zhouaini528** [comment]
你的服务器是哪里的？国内  还是国外？

**Comment by yeshili** [comment]
我现在是本地访问，然后我传上服务器也是一样，服务器是国内的呢！

**Comment by zhouaini528** [comment]
你本地翻墙没？   上传的服务器也是国内的？？？     huobi  okex  binance  都需要翻墙

**Comment by yeshili** [comment]
https://bz.jmw333.com/index.php/index/binance
https://bz.jmw333.com/index.php/index/huobi
这个是服务器

**Comment by yeshili** [comment]
不需要呀，OK我直接使用官方文档都可以成功

**Comment by zhouaini528** [comment]
你配置  里面 有没有设置   host??

**Comment by zhouaini528** [comment]
你稍等一下 ,我国内服务器 测试一下

**Comment by zhouaini528** [comment]
你加我QQ：465382251  方便沟通

**Comment by yeshili** [comment]
还真的是，ping了一下无法ping通，应该是我的网络问题。

还有一个，比特儿交易所，这个群里很大，期待下次看到支持这个！

**Comment by zhouaini528** [comment]
本地开发测试，需要你开启翻墙并配置响应的proxy=true
```php
$exchanges->setOptions([
    //Set the request timeout to 60 seconds by default
    'timeout'=>10,
    
    //If you are developing locally and need an agent, you can set this
    'proxy'=>true,   //需要开启这个
]);
```
所有的交易所都是需要翻墙的。okex  huobi  如果支持国内服务器，但是建议还是走国外服务器。因为API请求地址已经写死在代码里了。

你刚刚说的交易所是这个吧  https://www.gateio.la   我下来可以考虑接入进来。

最后就是  有什么问题  就issues哈

**Comment by yeshili** [comment]
是的，这个是比特儿https://www.gateio.la，后期期待加入这个。
我刚刚把源码放到德国服务器，就可以访问了。http://bz.yeshili.com.cn/index.php/index/binance

好的，谢谢！

**Comment by zhouaini528** [comment]
最后再给你一点意见。看你测试的方式是用的传统php-fpm方式，建议你用cli的模式，万一哪天你忘记删除代码了，可能会对你资产有安全问题。      比特儿我接下来会考虑加入它。

**Comment by yeshili** [comment]
好的，谢谢你的意见！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lin"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 晚上6:08
收件人: "zhouaini528/exchanges-php"<exchanges-php@noreply.github.com&gt;; 
抄送: "叶世立"<ye-shi-li@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhouaini528/exchanges-php] 你好，我现在很头痛，一直出现这个问题，这个问题怎么解决呢，我单独写OK,或者币安没有出现这个问题呢 (#5)





 
最后再给你一点意见。看你测试的方式是用的传统php-fpm方式，建议你用cli的模式，万一哪天你忘记删除代码了，可能会对你资产有安全问题。      比特儿我接下来会考虑加入它。
