### ISSUE TITLE
Do you have any plans to implement WebSocket

### ISSUE THREAD

**Issue by makaronnik** [zhouaini528/exchanges-php#9]
Do you have any plans to implement WebSocket connection to exchanges?  If yes, then when?  Most interested in Binance. Thanks!

**Comment by zhouaini528** [comment]
Our market price is websocket connection to exchanges. We don't do websocket order transaction. Do you have such a need? I'll consider joining it later.

**Comment by zhouaini528** [comment]
If you are not a high-frequency transaction, it is recommended to use REST HTTP for easier maintenance

**Comment by makaronnik** [comment]
Thanks for the answer!  I am interested in connecting via a web socket to receive changes in order statuses and changes in order book volumes, without having to make API requests every second.

**Comment by zhouaini528** [comment]
We also have such a requirement, not using PHP development, using GO development to do a part of the function. I still want to use PHP for development. I am quite busy recently. After a period of time, I will give priority to using websocket connection to exchanges in Binance.Thank you for your advice.

**Comment by makaronnik** [comment]
Ok, thank you!

**Comment by zhouaini528** [comment]
Hello, I give priority to the development of the okex version of websocket, I am ready to develop the binance version of websocket, you are welcome to give me some suggestions.

Okex [WebSocket](https://github.com/zhouaini528/okex-php/blob/master/README.md#Websocket)

**Comment by makaronnik** [comment]
Great! Thank you very much!

**Comment by zhouaini528** [comment]
I have finished a version of websocket, and if you find any problems, you can tell me
 
[binance](https://github.com/zhouaini528/binance-php/blob/master/README.md#Websocket)
